# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "outfitxr"
client_id = "4e478bc001bf7f8bd445c1804d39ca82"
application_url = "https://organisms-dee-panic-cache.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://organisms-dee-panic-cache.trycloudflare.com/auth/callback",
  "https://organisms-dee-panic-cache.trycloudflare.com/auth/shopify/callback",
  "https://organisms-dee-panic-cache.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-652e7786.myshopify.com"
