# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "outfitxr"
client_id = "4e478bc001bf7f8bd445c1804d39ca82"
application_url = "https://outfixer-shopify-2be3341ccfcf.herokuapp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://outfixer-shopify-2be3341ccfcf.herokuapp.com/auth/callback",
  "https://outfixer-shopify-2be3341ccfcf.herokuapp.com/shopify/callback",
  "https://outfixer-shopify-2be3341ccfcf.herokuapp.com/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
